name: Aegis
version: "2.2"
author: 7isenko
main: io.github._7isenko.aegis.Aegis
api-version: "1.20"
commands:
  event:
    description: Starts or stops your discord bot. "kick" kicks every member without role from discord.
    usage: /event start, /event stop, /event kick, /event add <num>, /event set <nick>, /event react
    permission: aegis.usage
permissions:
  aegis.usage:
    description: allows to use this plugin
    default: op